version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
    - ./src/example-plugin:/var/www/html/wp-content/plugins/example
    ports:
      - '8000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1

  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  dbdata:
